# Server
url: http://www.chilblane.com/wow-armory-redesign
baseurl: ""
exclude: [node_modules, src, Gemfile, Gemfile.lock, Gruntfile.js, package.json, README.md]
permalink: /:title

# Page meta
title: WoW Armory Redesign
description: Portfolio project redesigning World of Warcraft Armory pages, Daniel Singer (chilblane)
authors: Daniel Singer, Blizzard
og_image: http://bnetcmsus-a.akamaihd.net/cms/template_resource/fh/FHSCSCG9CXOC1462229977849.png
